### ISSUE TITLE
Responsive Bilder auf der Startseite!

### ISSUE THREAD

**Issue by lukasmoerchen** [dk248/Didaktik#11]

**Comment by lukasmoerchen** [comment]
@ch-bu

**Comment by ch-bu** [comment]
Lest euch einmal [diesen Artikel](http://www.w3schools.com/css/css_rwd_images.asp) durch. Ich würde euch empfehlen im CSS **background-size: cover** zu verwenden, so stellt ihr sicher, dass das Bild nicht falsch skaliert wird. Verwendet auch media-queries wie es in dem Artikel umgesetzt wird. Ich habe euch keinen Pull-Request gemacht, da ihr noch nicht die endgültigen Bilder hochgestellt habt. Erst dann macht es mehr Sinn.
