### ISSUE TITLE
Responsive Navbar

### ISSUE THREAD

**Issue by lukasmoerchen** [dk248/Didaktik#12]
@ch-bu Ich habe schon vor längerer Zeit die Navbar hinzugefügt. Die ist auch an kleinere Displays angepasst, d.h. alle Schaltflächen bis auf die Startseite verschwinden ab einer gewissen Größe und dafür kommt ein Burger-Button (?) über den man das Menü aufklappen sollte, sodass bei Bedarf alle Schaltflächen des Menüs angezeigt werden. Das Menü klappt jedoch bei Klick auf den Burger nicht auf.

Ich habe mich hier orientiert, finde aber den Fehler im Augenblick nicht: https://www.w3schools.com/howto/howto_js_topnav.asp

Es gibt im Augenblick eine header.html (für die normalen Seiten) und eine header-ch.html für die Seiten mit Herausforderungen, da dort ein Bild noch im Header sein soll.

**Comment by lukasmoerchen** [comment]
Habe es doch gerade irgendwie herausgefunden...

**Comment by lukasmoerchen** [comment]
@ch-bu ok, also jetzt funktioniert das Burger-Icon mit Menü aufklappen. Allerdings funktioniert das Dropdown Menü nicht richtig (es fehlt immer der unterste Eintrag).
Bei der header-ch.html gibt es noch einige Probleme die ich mir jetzt mal anschaue.

**Comment by ch-bu** [comment]
@lukasmoerchen Ich habe mir das Menu gerade angesehen. Es scheint gut zu funktionieren. Bei mir wird zumindest der letzte Eintrag im Dropdown (Impressum) angezeigt.

**Comment by lukasmoerchen** [comment]
@ch-bu auch wenn du unter 680px Bildschirm bist?
Dann verkleinert sich das Menü ja und der Burger erscheint rechts. Bei mir sieht es dann so aus:
![image](https://cloud.githubusercontent.com/assets/23659613/23207521/d725630e-f8f1-11e6-9a5e-ae5caabcaf9e.png)
Also im Dropdown Menü fehlt der letzte Eintrag.

**Comment by ch-bu** [comment]
@lukasmoerchen Du meinst das Untermenü. Ok, schau ich mir nachher mal an.

**Comment by ch-bu** [comment]
@lukasmoerchen Siehe Pull-Request. Achte darauf, dass ihr keine [divs in ul benutzten solltet](http://stackoverflow.com/questions/8557869/is-this-html-structure-valid-ul-div-li-li-div-li-li-div).

**Comment by lukasmoerchen** [comment]
@ch-bu das funktioniert leider nicht. siehe meine Antwort im pull-request.

**Comment by lukasmoerchen** [comment]
ich habe es jetzt einfach durch eine geänderte Reihenfolge im Menü gelöst, d.h. die Herausforderungen stehen im menü jetzt einfach vor der Lernumgebung. Anders ging es nicht.
