### ISSUE TITLE
Was mache ich mit den Daten aus dem Kontaktformular?

### ISSUE THREAD

**Issue by lukasmoerchen** [dk248/Didaktik#13]
@ch-bu 
https://www.w3schools.com/php/php_forms.asp
Hier wird ja nur gezeigt, wie ich die Daten anzeigen lassen kann, sobald die Person auf "Senden" drückt. Kann ich die Daten auch in txts speichern lassen oder so ähnlich?

**Comment by ch-bu** [comment]
@lukasmoerchen Beachte, dass du auf GitHub Pages [kein PHP ausführen kannst](http://stackoverflow.com/questions/10837946/how-to-publish-php-page-instead-of-html-at-github-to-demo-some-php-content). Ihr müsst daher eine andere Möglichkeit finden, die Daten zu speichern, sofern ihr das möchtet. Es gäbe zwar den [Local Storage](https://www.w3schools.com/html/html5_webstorage.asp), dieser zeigt aber nur Daten einzelner Nutzer an. Vielleicht hilft euch [Google Groups](https://support.google.com/sites/answer/1191206?hl=de). Das könnt ihr nämlich einbetten.

**Comment by lukasmoerchen** [comment]
Ich habe folgende Seite gefunden: https://www.templatemonster.com/blog/free-contact-form-services/
Werde mich morgen (Sonntag) mal daran setzen!
