### ISSUE TITLE
Impressum erstellen

### ISSUE THREAD

**Issue by lukasmoerchen** [dk248/Didaktik#16]
@M94JU24PLI12 @Tati-ana @dk248 

Ein Impressum muss erstellt werden (impressum.html). Am besten mit irgendwelchen Verweisen für Facebook/Twitter/WhatsApp (einfach mal Googeln, was es da für Textvorlagen gibt.) Außerdem sollte ins Impressum ein Verweis wegen der Lernumgebung rein. Der Link zum Impressum muss auch im header und footer eingetragen werden.

**Comment by M94JU24PLI12** [comment]
werde ich mir morgen oder Montag anschauen !

**Comment by M94JU24PLI12** [comment]
Erster Entwurf hochgeladen. Link zum Impressum noch nicht im Header und footer eingetragen. Werde ich aber am Montag noch machen.
