### ISSUE TITLE
Seite für Aufmerksamkeit erstellen

### ISSUE THREAD

**Issue by lukasmoerchen** [dk248/Didaktik#17]
@M94JU24PLI12 @Tati-ana @dk248 

einfach die motivation.html kopieren und die entsprechenden Inhalte/Titel/Texte etc. ersetzen.
Außerdem im header und auf der Startseite (in den Bildern der Kacheln) verlinken.

**Comment by dk248** [comment]
@lukasmoerchen gerade erstellt ... kannst du mal checken, ob es da ist

**Comment by lukasmoerchen** [comment]
Ja ist bei mir da, allerdings fehlen noch die Verlinkungen im header und auf der Startseite, aber das mache ich schnell. Super!
