### ISSUE TITLE
Seite für Komplexität erstellen

### ISSUE THREAD

**Issue by lukasmoerchen** [dk248/Didaktik#18]
Analog zu Aufmerksamkeit

Inhalte ersetzen und Verlinkungen einfügen.

**Comment by dk248** [comment]
mache gerade

**Comment by dk248** [comment]
fast fertig .... mir fehlt gerade den Beispiel ... @M94JU24PLI12 @Tati-ana 
@lukasmoerchen du musst die genaue Veränderung machen wie in der Aufmerksamkeit-Seite (die genaue Veränderung habe ich nicht gelesen)
