### ISSUE TITLE
Beweglicher Header weniger durchsichtig machen

### ISSUE THREAD

**Issue by Tati-ana** [dk248/Didaktik#19]
Wenn man nach unten scrollt bleibt der Header zwar wie gewollt am Seitenrand oben hängen, allerdings so transparent, dass man ihn bei dunklem Hintergrund (z.B. das Tafelbild) garnicht sieht. Klickt man dort etwas vom Header an, so wird nicht dieser Link gewählt sonder der, der sich in diesem Moment hinter dem Header befindet (z.B. Herausforderung Motivation). Außerdem gibt es bei diesem kleinen Header kein Drop-Down-Menu für die Herausforderungen, was an und für sich nicht schlimm ist. Allerdings sollte entschieden werden, wohin der User kommt, wenn er da auf die Herausforderungen klickt - mindestens auf die Startseite?

**Comment by lukasmoerchen** [comment]
Ich habe den ganzen header-firlefanz mal wieder gelöscht. Der header bleibt jetzt einfach oben und fertig. dann macht er auch keine Probleme. Dann ist alles in Ordnung oder gibts trotzdem noch irgendwelche Fehler?

**Comment by Tati-ana** [comment]
Alles Bestens:)
