### ISSUE TITLE
Kontakt auch bei den Herausforderungsseiten als Header?

### ISSUE THREAD

**Issue by Tati-ana** [dk248/Didaktik#21]
Ich finde (meinen testenden Mitbewohnern zustimmend), dass auffällige Kontaktformular auf den Herausforderungsseiten zu sehr die Aufmerksamkeit auf sich zieht. Ich würde es deshalb hier gerne raus nehmen. Im Header könnte man es doch dann so verlinken, dass man mit einem Klick direkt auf das Kontaktformular unten an der Startseite weitergeleitet wird? Was meint ihr?

**Comment by lukasmoerchen** [comment]
ich würde es eigentlich da unten lassen und erstmal ausprobieren, ob man den Einleitungstext noch ein bisschen prominenter macht und ein Panel schon aufgeklappt ist (das sollte irgendwie funktionieren).

**Comment by Tati-ana** [comment]
Gut, probieren wir das mit dem prominenteren Einleitungstext. Kann man den Zeilenabstand n bisschen vergrößern? Wo find ich denn den allgemeinen Schriftstile? (Ein Panel schon aufgeklappt würd ich eher nicht machen, weil man dem User dann die Entscheidung abnimmt, was er lesen möchte)

**Comment by lukasmoerchen** [comment]
war das jetzt geklärt? @Tati-ana

**Comment by Tati-ana** [comment]
Ja, kann so bleiben:)
