### ISSUE TITLE
Impressum 

### ISSUE THREAD

**Issue by M94JU24PLI12** [dk248/Didaktik#23]
Auf Lernumgebung der anderen Gruppe verweisen, Kopf mit Adresse ... überarbeiten

**Comment by M94JU24PLI12** [comment]
erledige ich heute Abend

**Comment by M94JU24PLI12** [comment]
Bild aus Drehbuch ins Impressum einfügen !

**Comment by M94JU24PLI12** [comment]
Habe im Impressum nun ein Platzhalterbild eingefügt, hier kommt noch das Bild aus der letzten Version des Drehbuches hin.

**Comment by lukasmoerchen** [comment]
Ich habe mal noch das wie auf den Motivationsseiten angepasst. Wenn das Platzhalterbild lizenzfrei ist, würde ich sogar lieber das verwenden.

**Comment by M94JU24PLI12** [comment]
Danke ! Ich glaube das das Bild leider nicht lizenzfrei ist, zumindest habe ich nicht herausgefunden, dass es lizenzfrei ist. Ich habe hier mal noch ein Link für ein alternatives Impressumbild, das lizenzfrei sein müsste: https://www.delphimagazin.de/wp-content/uploads/2015/09/Impressum.jpg
Sollen wir dieses Bild nehmen, oder hat jemand ein passenderes, lizenzfreies Bild?

**Comment by lukasmoerchen** [comment]
ok, ja ich nehme dann das neue Bild hier vom Link und ersetze das später.

**Comment by M94JU24PLI12** [comment]
perfekt, Dankeschön ! :)

**Comment by lukasmoerchen** [comment]
Done.
