### ISSUE TITLE
Eventuell: eigene Seite "Über Uns" hinzufügen. Alternativ Hintergrundbild für Einleitungstext-Block raussuchen (Tati)

### ISSUE THREAD

**Issue by Tati-ana** [dk248/Didaktik#27]
Falls noch Zeit ist. Einleitungstext kann bis auf ersten Satz dann auch darin stehen.

**Comment by Tati-ana** [comment]
Hab das jetzt ein bisschen umgestaltet. Header ist weiter unten (wie auf den anderen Seiten), Willkommensbalken in dem dunkelrot (das dunkelgrün sah mit dem Header-Markieren-Hellgrün irgendwie komisch aus) und direkt darunter den Einleitungstext mit Hintergrundbild. Passt das?

**Comment by Tati-ana** [comment]
Hab statt diesem Hintergrundbild auch das mit den Blocklinien von weiter unten ausprobiert, aber das wirkt wesentlich strenger (meinen meine Mitbewohner);)

**Comment by lukasmoerchen** [comment]
hab noch die Seite hinzugefügt, allerdings primär zur Präsentation der Website und nicht zur Information für Nutzer.
