### ISSUE TITLE
Footer nicht eingebunden

### ISSUE THREAD

**Issue by lukasmoerchen** [dk248/Didaktik#4]
Die footer.html ist nicht nicht in die index.html eingebunden.

**Comment by ch-bu** [comment]
Es gibt mehrere Möglichkeiten. Entweder ihr verwendet [dieses Skript](http://www.w3schools.com/howto/howto_html_include.asp) oder geht über [JQuery](http://stackoverflow.com/questions/15320801/how-to-include-an-html-file-with-jquery). Bei beiden Lösungen müsst ihr allerdings einen lokalen Server laufen lassen.  Ich würde euch empfehlen, zunächst [Python 3](https://www.python.org/downloads/) zu installieren und danach den [SimpleHttpServer von Python](http://stackoverflow.com/questions/17351016/set-up-python-simplehttpserver-on-windows) zu verwenden. Ich probiere es einmal aus und mache euch einen Pull request.
